### ISSUE TITLE
Auto-inflate does not support MS-style Deflate compression

### ISSUE THREAD

**Issue by stevenkaras** [httprb/http#415]
Even though the [IANA][iana] declared deflate compression to be inside a zlib wrapper, Microsoft chose to implement deflate compression as [raw streams][adler].

[iana]: http://www.iana.org/assignments/http-parameters/http-parameters.xhtml#content-coding
[adler]: https://stackoverflow.com/a/9186091/152335

```ruby
require 'http'

response = HTTP.use(:auto_inflate).headers("Accept-Encoding" => "deflate").get("http://www.bing.com")
response.body.to_s
```

There's a related bug report in [Net::HTTP][upstream], although it doesn't mention the underlying issue.

[upstream]: https://bugs.ruby-lang.org/issues/11268

I've observed it in Ruby 2.3.1 and http gem 2.2.1.

One possible solution would be a warning if the accept encoding header contains deflate, but ideally it would fall back on deflating the raw stream if the header check failed.

**Comment by ixti** [comment]
Hm. Good catch, but I don't think we should do anything. We inflate stream according to specs. The fact that Microsoft sends invalid deflated data (non-RFC compliant in this case) is an exceptional case.

IMHO we should just emphasize that in README and promote to use `"Accept-Encoding" => "gzip"`.

**Comment by stevenkaras** [comment]
If I thought it would push MS to fix their software, then I'd be 100% for it. But given that the fallback handling is more or less straightforward and easy to document, I'd prefer to see support for it, and documented.

**Comment by ixti** [comment]
In the SO you linked, Mark Adler said:

> However early Microsoft servers would incorrectly deliver raw deflate for "Deflate" (i.e. just RFC 1951 data without the zlib RFC 1950 wrapper). This caused problems, browsers had to try it both ways, and in the end it was simply more reliable to only use gzip.

Also, I would like to highlight some of [loose the wait](https://zoompf.com/blog/2012/02/lose-the-wait-http-compression) article:

> It should be also noted that all browsers that support DEFLATE also support GZIP, but all browser that support GZIP do not support DEFLATE. Some browsers, such as Android, don’t include deflate in their Accept-Encoding request header.

> The Apache module which handles all HTTP compression is mod_deflate. Despite its name, mod_deflate don’t not support deflate at all.

> Nginx, like Apache, does not support deflate at all. It will only send GZIP compressed responses. Sending an Accept-Encoding: deflate request header will result in an uncompressed response.

With all above, I would like to emphasize last bit of Mark Adler's quote, that it was (and in fact *is*): **simply more reliable to only use gzip**. And here's small experiment with bing.com:

``` ruby
require "http"

response = HTTP.use(:auto_inflate)
  .headers("Accept-Encoding" => "deflate, gzip")
  .get("http://www.bing.com")

response["Content-Encoding"] # => "gzip"
response.to_s[0...42]        # => "<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1"
```

Even if you will set quantifier of `gzip` to be low, e.g.: `"deflate, gzip; q=0.1"`, bing will prefer it over deflate and will send deflate ONLY if you will explicitly ask for deflate ONLY.

I don't find such fallback a straightforward solution. There's no RFC for that. And Microsoft-IIS usage is insignificant (IMO) compared to apache and nginx. So I don't see point in adding hack just for that defective server.

@httprb/core please, chip in!

**Comment by puzrin** [comment]
@stevenkaras do you have example from real world when server supports deflate and does not support gzip? IMHO doing something for deflate is a waste of time.

**Comment by stevenkaras** [comment]
I ran across the issue due to this site which strongly prefers deflate over gzip ("gzip, deflate; q=0.5" results in deflate):

https://www.lytx.com/en-us/blog/

I haven't found any others that exhibit the behavior. Regarding the behavior of MS servers, it may have originated in very old versions, but the headerless deflate is the current behavior of IIS 10.

**Comment by puzrin** [comment]
@stevenkaras problem is that you should NOT allow deflate in accepted compressors if you wish 100% correct behaviour. Why don't you ask gzip only?

**Comment by ixti** [comment]
So, in other words, https://www.lytx.com/en-us/blog/ not only does not follows `deflate` content encoding specs, but it also improperly handles accept-encoding field.

Of course it's possible to try inflate raw deflate body, but the logic for that will make inflation complex for no good. Let's take a look on how that logic will look like:

``` ruby
module HTTP
  class Response
    class Inflater
      attr_reader :connection

      def initialize(connection)
        @connection = connection
      end

      def readpartial(*args)
        chunk = @connection.readpartial(*args)
        if chunk
          chunk = inflate(chunk)
        elsif !zstream.closed?
          close
        end
        chunk
      end

      private

      def inflate(chunk)
        chunk = zstream.inflate(chunk)
        @zstreaming = true
        chunk
      rescue Zlib::DataError => e
        raise unless e.message == "incorrect header check"
        raise if defined?(@zstreaming) || defined?(@zstream_modified)

        
        @zstream_modified = true
        @zstream = Zlib::Inflate.new(-Zlib::MAX_WBITS)
        retry
      end

      def zstream
        @zstream ||= Zlib::Inflate.new(32 + Zlib::MAX_WBITS)
      end

      def close
          zstream.finish
          zstream.close
      end
    end
  end
end
```

Comparing to current state of inflater - this is a nightmare. In face that this is a really rare case, more than that, in face that it will be HARD to find server that responds with raw deflate only and not supporting gzip, I find adding such hack into http gem absolutely unacceptable.

For such a rare case one can handle inflating on his own:

``` ruby
response = HTTP["Accept-Encoding" => "deflate"].get("https://www.lytx.com/en-us/blog/")
inflater = Zlib::Inflate.new(-Zlib::MAX_WBITS)
body = inflater.inflate(response.to_s)
inflater.finish
inflater.close
```

**Comment by stevenkaras** [comment]
@puzrin TBH, I had copied the headers from a captured Firefox session. Very little about browsers has to do with 100% acceptable behavior. Getting even 50% is a very good day.

@ixti that was more or less what I came up with as well. On further reflection, I feel the best place for this is upstream, as Zlib already handles both gzip and deflate (RFC1950,1951).

In either case, the current behavior should be documented (the discussion here seems to be sufficient). Go ahead and close this if you concur it should be fixed upstream instead of here (I'll ping back if they refuse to fix).

**Comment by evgo2017** [comment]
I think promote to use `"Accept-Encoding" => "gzip"` is right, and fix the error is right too,.

Because most users don't know about the error, it will take them a lot of time (just like me), even at the end, the error remained unsolved. I think you don't want to see this.

I encountered the error when I use other tools, finally I succeeded because of this document: [Node.js zlib deflateraw](https://nodejs.org/dist/latest-v10.x/docs/api/zlib.html#zlib_class_zlib_deflateraw).

Have the ability to do better, why not do it?

**Comment by tarcieri** [comment]
> Have the ability to do better, why not do it?

Supporting weird edge cases like this comes at the cost of code complexity and reduced maintainability. See @ixti's example above.

**Comment by evgo2017** [comment]
@tarcieri  There is a sentence in this  [Support raw deflate streams](https://github.com/sindresorhus/got/issues/303#issuecomment-301229942) : "That way everyone would benefit instead of just Got users."

**Comment by evgo2017** [comment]
Your option is correct, but availability? I hope you can think more about it. 

This is just a suggestion. Thanks for your reply.

**Comment by tarcieri** [comment]
@evgo2017 if I understand the linked issue correctly (perhaps I don't), they're suggesting an upstream zlib fix?

**Comment by evgo2017** [comment]
I have fully expressed my point of view, albeit very general

**Comment by tarcieri** [comment]
If I understand the linked suggestion correctly, I think the next steps are either to file a bug at https://bugs.ruby-lang.org/

**Comment by tarcieri** [comment]
And if that's the case, I think we should close the issue, which I'll do now.
